package virtual_account

import (
	"context"
	"net/http"

	"github.com/DoWithLogic/go-bca-sdk/internal/transport"
)

// VirtualAccountInquiryRequest represents a request to inquire
// about a Virtual Account.
type VirtualAccountInquiryRequest struct {
	// PartnerServiceID is the 8-character service identifier derived
	// from the X-PARTNER-ID. It must be left-padded with spaces if
	// it contains fewer than 8 characters.
	PartnerServiceID string `json:"partnerServiceId"`

	// CustomerNo is the unique customer number, up to 18 digits.
	CustomerNo string `json:"customerNo"`

	// VirtualAccountNo is the Virtual Account number consisting of
	// the 8-character PartnerServiceID followed by the CustomerNo.
	VirtualAccountNo string `json:"virtualAccountNo"`

	// InquiryRequestID is the unique identifier for the inquiry
	// generated by BCA.
	InquiryRequestID string `json:"inquiryRequestId"`

	// AdditionalInfo contains optional custom information for
	// the Virtual Account inquiry.
	AdditionalInfo any `json:"additionalInfo,omitempty"`
}

// VirtualAccountInquiryResponse represents the response from the
// Virtual Account inquiry API.
type VirtualAccountInquiryResponse struct {
	ResponseCode       string             `json:"responseCode"`
	ResponseMessage    string             `json:"responseMessage"`
	VirtualAccountData VirtualAccountData `json:"virtualAccountData"`
}

// VirtualAccountData contains the payment and Virtual Account
// information returned by the inquiry.
type VirtualAccountData struct {
	// PaymentFlagStatus indicates the payment status defined by
	// the partner.
	//
	// Possible values:
	//   - "00": Success payment flag.
	//   - "01": Payment flag rejected by the partner.
	//   - "02": Payment flag timeout between the switcher and partner.
	//   - "03": Payment flag is pending between BCA and the partner.
	PaymentFlagStatus string `json:"paymentFlagStatus"`

	// PaymentFlagReason contains the reason for the payment status
	// in multiple languages.
	PaymentFlagReason PaymentFlagReason `json:"paymentFlagReason"`

	// PartnerServiceID is the 8-character service identifier derived
	// from the X-PARTNER-ID.
	PartnerServiceID string `json:"partnerServiceId"`

	// CustomerNo is the unique customer number.
	CustomerNo string `json:"customerNo"`

	// VirtualAccountNo is the Virtual Account number consisting of
	// the PartnerServiceID followed by the CustomerNo.
	VirtualAccountNo string `json:"virtualAccountNo"`

	// InquiryRequestID is the unique identifier of the inquiry.
	InquiryRequestID string `json:"inquiryRequestId"`

	// PaymentRequestID is the unique identifier of the payment,
	// when a payment has occurred. It matches InquiryRequestID.
	PaymentRequestID string `json:"paymentRequestId"`

	// PaidAmount contains the total amount paid by the customer
	// through BCA.
	PaidAmount Amount `json:"paidAmount"`

	// PaidBills contains the hexadecimal representation of the
	// binary paid-bills flag.
	PaidBills string `json:"paidBills,omitempty"`

	// TotalAmount contains the total amount of the transaction.
	TotalAmount Amount `json:"totalAmount"`

	// TransactionDateTime is the BCA internal transaction timestamp
	// with timezone in ISO-8601 format.
	TransactionDateTime string `json:"trxDateTime,omitempty"`

	// TransactionDate is the date and time when the payment occurred.
	TransactionDate string `json:"transactionDate"`

	// ReferenceNo is the payment authorization code generated by BCA.
	ReferenceNo string `json:"referenceNo,omitempty"`

	// PaymentType indicates the type of payment.
	PaymentType string `json:"paymentType,omitempty"`

	// FlagAdvise indicates whether the transaction is a retry
	// notification.
	FlagAdvise string `json:"flagAdvise,omitempty"`

	// BillDetails contains details for individual bills.
	BillDetails []BillDetail `json:"billDetails,omitempty"`

	// FreeTexts contains optional messages to be displayed in
	// the payment channel.
	FreeTexts []FreeText `json:"freeTexts,omitempty"`

	// AdditionalInfo contains optional partner-specific information.
	AdditionalInfo any `json:"additionalInfo,omitempty"`
}

// PaymentFlagReason contains the reason for a payment status
// in English and Bahasa Indonesia.
type PaymentFlagReason struct {
	English   string `json:"english"`
	Indonesia string `json:"indonesia"`
}

// BillDetail contains payment information for an individual bill.
type BillDetail struct {
	// BillCode is the bill code selected by the customer.
	BillCode string `json:"billCode,omitempty"`

	// BillNo is the bill number provided by the partner.
	BillNo string `json:"billNo"`

	// BillName is the name of the bill.
	BillName string `json:"billName,omitempty"`

	// BillShortName is the short name of the bill displayed to
	// the customer.
	BillShortName string `json:"billShortName,omitempty"`

	// BillDescription contains the bill description in multiple languages.
	BillDescription BillDescription `json:"billDescription"`

	// BillSubCompany is the partner's product code.
	BillSubCompany string `json:"billSubCompany"`

	// BillAmount contains the transaction amount for the bill.
	BillAmount Amount `json:"billAmount"`

	// AdditionalInfo contains optional bill-specific information.
	AdditionalInfo any `json:"additionalInfo,omitempty"`

	// BillReferenceNo is the bill authorization code generated by BCA.
	BillReferenceNo string `json:"billReferenceNo"`

	// Status is the payment status for this specific bill.
	Status string `json:"status"`

	// Reason contains the payment status reason in multiple languages.
	Reason PaymentReason `json:"reason"`
}

// BillDescription contains the bill description in English
// and Bahasa Indonesia.
type BillDescription struct {
	English   string `json:"english"`
	Indonesia string `json:"indonesia"`
}

// PaymentReason contains the payment status reason in English
// and Bahasa Indonesia.
type PaymentReason struct {
	English   string `json:"english"`
	Indonesia string `json:"indonesia"`
}

// FreeText contains optional text displayed in the payment channel.
type FreeText struct {
	English   string `json:"english"`
	Indonesia string `json:"indonesia"`
}

// Amount represents a monetary amount and its ISO 4217 currency.
type Amount struct {
	Value    string `json:"value"`
	Currency string `json:"currency"`
}

// VirtualAccountInquiry retrieves the payment status of a Virtual Account.
func (v *VirtualAccountService) VirtualAccountInquiry(ctx context.Context, request VirtualAccountInquiryRequest, externalID string) (*VirtualAccountInquiryResponse, error) {
	var response VirtualAccountInquiryResponse
	err := v.t.Do(
		ctx,
		transport.Request{
			Method: http.MethodPost,
			Path:   "/openapi/v2.0/transfer-va/status",
			Body:   request,
			Headers: http.Header{
				"X-EXTERNAL-ID": []string{externalID},
			},
		},
		&response,
	)
	if err != nil {
		return nil, err
	}

	return &response, nil
}
